---
title: "Lexie"
author: "Cécile SAUDER"
date: "2017-07-12"
output: html_document
---


## Ta naissance 
On est mardi 11, déjà 2 jours qu'on a dépassé la date prévue de ton arrivée, maman et papa s'impatientent, on a hate de te voir. Maman fait du fitness pour t'aider à trouver la sortie. Et on décide d'aller diner au resto, on va au libanais Al-Manara, et en sortant toujours des contractions mais qui commencent à être un peu plus douloureuses. C'est vers minuit, une fois rentrés à la maison, maman essaie de se détendre sur la balle, puis de se coucher, en se disant que ça va peut-être passer en dormant, papa est couché aussi, mais finalement la position allongée n'est pas super pour la douleur des contractions, alors on décide de partir à la maternité. On prépare les affaires, papa les descend à la voiture, et nous voilà partis. Papa a décidé de faire un ptit détour en loupant la sortie, pour être sûre que tu arrivais bien... Maman commence à avoir des contractions bien douloureuse et veut une péridurale. 
Une fois à la maternité, surprise à la porte habituelle, l'entrée de nuit ne se fait pas là, un papier dit de faire le tour du bâtiment, aïe aïe aïe, le tour d'un énorme bâtiment avec des contractions c'est pas évident ! Mais bon on a fait le tour, fini par trouver une porte ouverte, et quelqu'un pour nous indiquer où aller, et nous voilà dans la salle d'accouchement, box 2 :) 
Il est 2h du matin et au premier examen du col, dialtation à 3/4. A 4h du matin, la peridurale était posée et maman avait moins mal, du coup on a pu se reposer entre les examens des sage femmes pour voir si le travail avançait. Et il avançait, mais lentement, très lentement, toute la nuit et une bonne partie de la journée est passée, papa est allé se chercher à manger, maman pouvait pas manger pendant le travail et de toute façon elle avait déjà bien du mal à digérer le resto libanais à cause des contractions. Puis l'après-midi, jusqu'à ce que le col de maman (ta porte de sortie) soit bien ouvert pour que tu puisses passer. Les contractions n'étaient vraiment plus très fortes à ce moment là, mais on était très pressés de te voir alors maman a poussé bien fort quelques fois. Quand ta tête est apparue, une des sage femmes, qui était plutôt drôle, a proposé de te faire un shampoing, tu as donc eu ton premier shampoing, ça nous a beaucoup fait rire, et penser à ta soeur qui n'aime pas trop faire les shampoings.  Puis tu as vite passé les 3 étapes du  bassin pour te retrouver dans les bras de maman qui était aux anges. Papa a coupé ton cordon, puis on a pu te contempler et prendre en photo, tu étais déjà magnifique. 60 kg, 34 cm de tour de tête, et 50 cm, parfaite :) 

## Séjour à la maternité
Juste après ta naissance, on a attendu un moment en salle d'accouchement car c'était le changement d'équipe, puis on nous a monté toutes les 2 dans la chambre, accompagnées de papa. Ca faisait pas loin de 24h qu'on avait laissé Tigrou seul à la maison, alors papa nous a aidé à nous installer un moment puis il a fallu qu'il rentre s'occuper un peu de Tigrou. Maman a donc passé 4 nuits avec toi à la maternité et papa était avec nous tous les jours. Les sage-femmes et les auxilliaires de puericulture nous on montré comment te faire prendre le bain, te nettoyer les yeux, le nez, le cordon, changer tes couches. Papa et maman ont fait plein de peau à peau avec toi, surtout les 2 premiers jours pour te réchauffer car ta température était descendue à 35.5°C. On t'a aussi rajouté du lait à la seringue et à la paille pour que tu reprennes du poids, maman a passé une nuit longue et difficile, tu pleurais et tu voulais pas dormir dans ton lit, heureusement que les sages femmes l'ont aidé. ça a bien marché, le lendemain tu avais repris un peu de poids, et tu avais même un peu trop chaud, on a du te découvrir finalement, plus de brassière et chaussons pour dormir, juste le body et un petit pyjama léger. 
 

## Retour à la maison
Dimanche 16 juillet, après 4 nuits à la maternité après ta naissance (donc 5 nuits), on a enfin pu rentrer à la maison, maman avait bien appris à t'allaiter, tu têtais très bien, la montée de lait était là. Papa et maman savaient maintenant te faire prendre ton bain, nettoyer les yeux, le nez, le cordon etc... Il faisait très chaud dehors, il ne restait plus qu'à réussir à mettre le cosy bien attaché dans la voiture pour voyager en toute sécurité. ça a pris un moment pour réussir à mettre la ceinture correctement, on a pas été trop de 2 pour comprendre le système. Papa t'abritait du soleil avec son chapeau de Sherlock Holmes pendant ce temps. Et hop une fois bien installé en voiture, maman à côté de toi pour vérifier que tout va bien, retour à la maison :) 
Une fois à la maison, 
## Première nuit à la maison

T'as été un ange, pas un cri, t'as laissé tes parents faire des gros dodos de 3h. Maman a anticipé tes fringales et papa a changé tes couches qui commence à être bien rempli. Caca jaune et granuleux avaient dit les sages femmes, c'est exactement ça :D On dirait de la moutarde à l'ancienne... 

## Petit cadeau
Lundi 17 juillet, les 2 filles airbnbs belges qui étaient là ces 2 derniers jours t'ont offert un super hochet hyppopotame très mignon et très doux. 

## Première fois avec mamie Véro et Thierry, avec ta grande-soeur Alix, et première balade à poussette dans Montpellier
Mardi 18 juillet a été un jour plein de premières fois pour toi. D'abord mamie Véro, la maman de papa, et Thierry son compagnon sont venus te voir, et t'ont ramené 3 gros cartons d'habits et un joli doudou avec des grandes jambes et des grands bras, puis ta grande-soeur Alix, qui rentrait juste de vacances à Marseille et Embrun nous a fait la surprise de venir te voir aussi. Mamie Véro était bien contente de voir ses 2 petites filles à la fois. Pendant que Thierry allait chercher les cartons, monsieur Tigrou en a profité pour se faire la malle. Quel coquin ! On a mangé avec tous les 5 pendant que tu te reposais, puis après manger mamie Véro et Thierry ont repris la route pour Dauphin et on est allés se balader avec Alix en ville, ta première balade à poussette, et on a pris une glace en ville (enfin les grands parce que toi tu n'as pas encore le droit bien sûr). On a continué de chercher Tigrou en allant faire des tours dans l'impasse et en regardant sous les voitures mais non, pas de Tigrou. Maman a fini par le retrouver à la nuit tombée, après une nième recherche sous les voitures de l'impasse, en rentrant dans l'immeuble en secouant les croquette, qui voilà qui remontait tranquillement l'escalier de la cave... Tigrou ! 

## Tes grands-parents, ta tante Perle et son chien Maya viennent te voir à Montpellier


## Premières vacances à Arcachon avec la visite de ton grand-père Jehan-Phi et de Domi

## Ta soeur te calme en te jouant de la guitare
Quand tu pleures, Alix sort sa guitare et te joue Greensleeves et d'autres morceaux, ça marche très bien

## Retour de ton tonton Guillaume de Côte d'Ivoire
Lundi 30 octobre, nous avons fait la route vers Arcachon avec tonton Guigui et sa copine Alice pour la semaine. Au début tu pleurais quand tu le voyais avec sa grosse barbe et sa délicatesse ! Mais c'est vite passé, mardi il t'a apprivoisé et mercredi il a pu jouer avec toi et te faire rire. On a fait une grosse séance photo avec les petits habits qu'il t'a offert, ainsi qu'avec le costume de citrouille d'Halloween cousu vite fait par maman la veille, je le referais en plus joli avec la machine à coudre pour l'an prochain quand on sera de retour à la maison. 